add_executable(threadPool_test threadPool_test.cpp)
target_link_libraries(threadPool_test PRIVATE MyEventBus::Core)
target_compile_features(threadPool_test PRIVATE cxx_std_17)

add_executable(EventDispatcher_test EventDispatcher_test.cpp)
target_link_libraries(EventDispatcher_test PRIVATE MyEventBus::Core)
target_compile_features(EventDispatcher_test PRIVATE cxx_std_17)

add_test(NAME threadPool_test COMMAND threadPool_test)
add_test(NAME EventDispatcher_test COMMAND EventDispatcher_test)
